// Docs: https://pest.rs/book
// Editor: https://pest.rs/#editor

WHITESPACE = _{ " " | NEWLINE } 

//  Primitive data types
boolean = { "true" | "false" }
number = @{ "-"? ~ ASCII_DIGIT+ ~ ("." ~ ASCII_DIGIT+)? ~ !"." }
//char = @{ !"'" ~ (ANY)? }

char = { ANY? }

// string moon literal
// str = { (!("\"") ~ (ANY | WHITESPACE)*)? }

// Values
literal = { ( boolean | number | "'" ~ char ~ "'" /* | "\"" ~ string ~ "\""*/ ) }

program = { SOI ~ (literal | WHITESPACE)* ~ EOI }
